#!/bin/bash

# ============================================================
# MINING MANAGER v11.3 (Fix: Status Check Permissions)
# ============================================================

# Define Paths
CONFIG_DIR="$HOME/.config/mining-manager"
ENV_FILE="$CONFIG_DIR/mining.env"
WATCHDOG_SCRIPT="$CONFIG_DIR/watchdog_runner.sh"
WATCHDOG_PID_FILE="$CONFIG_DIR/watchdog.pid"
MINER_PID_FILE="$CONFIG_DIR/xmrig.pid"
LOG_FILE="$CONFIG_DIR/miner.log"
DEBUG_LOG="$CONFIG_DIR/debug.log"
MODE_FILE="$CONFIG_DIR/mode"

# Detect absolute path to bash in Termux
TERMUX_BASH=$(command -v bash)

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

# --- 1. INITIAL CHECKS ---

if [ "$(id -u)" -eq 0 ]; then
    echo -e "${YELLOW}Warning: You are running this script as ROOT.${NC}"
    echo "Please run as a normal user. The script will ask for sudo internally."
    read -p "Press Enter to continue anyway..."
fi

mkdir -p "$CONFIG_DIR"
touch "$LOG_FILE" "$DEBUG_LOG"
chmod 777 "$LOG_FILE" "$DEBUG_LOG" 2>/dev/null

# --- 2. AGGRESSIVE AUTO-REPAIR ---

fix_binary_path() {
    if [ -f "$ENV_FILE" ]; then
        source "$ENV_FILE"
        if [ ! -f "$CPU_BIN" ] && ! command -v "$CPU_BIN" >/dev/null 2>&1; then
            echo -e "${RED}Error: Configured binary '$CPU_BIN' missing.${NC}"
            echo -e "${BLUE}Scanning for system XMRig...${NC}"
            SYSTEM_BIN=$(command -v xmrig)
            if [ -z "$SYSTEM_BIN" ]; then
                echo -e "${YELLOW}System XMRig not found. Installing...${NC}"
                pkg install -y xmrig
                SYSTEM_BIN=$(command -v xmrig)
            fi
            if [ -x "$SYSTEM_BIN" ]; then
                echo -e "${GREEN}Repaired! Using: $SYSTEM_BIN${NC}"
                sed -i "s|^CPU_BIN=.*|CPU_BIN=$SYSTEM_BIN|" "$ENV_FILE"
                CPU_BIN=$SYSTEM_BIN
                sleep 1
            else
                echo -e "${RED}CRITICAL: Auto-repair failed.${NC}"
                read -p "Press Enter..."
            fi
        fi
    fi
}

# --- 3. INSTALLATION ---

install_deps() {
    echo -e "${BLUE}Installing dependencies...${NC}"
    pkg update -y
    pkg install -y git cmake libuv openssl clang make hwloc pkg-config termux-tools jq procps grep tsu
    if ! command -v sudo &> /dev/null; then echo -e "${RED}Error: 'sudo' missing.${NC}"; return 1; fi
}

compile_xmrig() {
    echo -e "${CYAN}=== COMPILING XMRIG ===${NC}"
    if ! command -v cmake &> /dev/null; then pkg install -y git cmake libuv openssl clang make hwloc pkg-config; fi
    cd "$HOME"
    rm -rf "$HOME/xmrig"
    if [ -d "xmrig" ]; then cd xmrig && git pull; else git clone https://github.com/MoneroOcean/xmrig.git && cd xmrig; fi
    rm -rf build && mkdir -p build && cd build
    echo -e "${BLUE}Configuring (No HWLOC/CUDA/OpenCL)...${NC}"
    cmake .. -DWITH_OPENCL=OFF -DWITH_CUDA=OFF -DWITH_HWLOC=OFF -DCMAKE_BUILD_TYPE=Release
    echo -e "${BLUE}Compiling...${NC}"
    make -j$(nproc)
    if [ -f "xmrig" ]; then echo -e "${GREEN}Success!${NC}"; return 0; else echo -e "${RED}Failed.${NC}"; return 1; fi
}

install_menu() {
    clear
    echo -e "${CYAN}=== INSTALL WIZARD ===${NC}"
    echo "1. Install Package (Recommended)"
    echo "2. Compile Source"
    echo "3. Skip"
    read -p "> " ch
    case $ch in
        1) pkg install -y xmrig; BIN=$(command -v xmrig) ;;
        2) compile_xmrig && BIN="$HOME/xmrig/build/xmrig" || BIN=$(command -v xmrig) ;;
        *) BIN=$(command -v xmrig) ;;
    esac
    [ -z "$BIN" ] && BIN="xmrig"
    echo "$BIN" > "$CONFIG_DIR/bin_path"
}

setup_config() {
    install_menu
    BIN_PATH=$(cat "$CONFIG_DIR/bin_path")
    rm "$CONFIG_DIR/bin_path"
    echo "AUTO" > "$MODE_FILE"
    read -p "Pool [gulf.moneroocean.stream:10128]: " pool; pool=${pool:-gulf.moneroocean.stream:10128}
    read -p "Wallet: " wallet
    read -p "Worker [AndroidWorker]: " worker; worker=${worker:-AndroidWorker}
    cat <<EOF > "$ENV_FILE"
CPU_BIN=$BIN_PATH
CPU_SERVER=$pool
CPU_WALLET=$wallet
CPU_WORKER=$worker
CPU_THREADS=$(nproc)
EOF
}

# --- 4. BACKGROUND SERVICE (ROOT LOGIC) ---

generate_watchdog_script() {
    cat <<EOF > "$WATCHDOG_SCRIPT"
#!${TERMUX_BASH}
# WATCHDOG SCRIPT (v11.3) - Generated by mining_manager.sh
ENV_FILE="${ENV_FILE}"
MODE_FILE="${MODE_FILE}"
MINER_PID_FILE="${MINER_PID_FILE}"
LOG_FILE="${LOG_FILE}"

# Make the PID file readable by the user
touch "\$MINER_PID_FILE"
chmod 644 "\$MINER_PID_FILE"

if [ ! -f "\$ENV_FILE" ]; then
    echo "\$(date): CRITICAL - Config file not found. Exiting." >> "\$LOG_FILE"
    exit 1
fi
source "\$ENV_FILE"
if [ -z "\$CPU_BIN" ] || [ -z "\$CPU_SERVER" ] || [ -z "\$CPU_WALLET" ]; then
    echo "\$(date): CRITICAL - Essential variables are not set. Exiting." >> "\$LOG_FILE"
    exit 1
fi
export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
if [ -w /proc/sys/vm/nr_hugepages ]; then echo 1280 > /proc/sys/vm/nr_hugepages; fi
is_screen_on() {
    if dumpsys window policy | grep -q "mScreenOnFully=true"; then return 0; fi
    val=\$(cat /sys/class/backlight/panel0-backlight/brightness 2>/dev/null)
    if [ "\$val" ] && [ "\$val" -gt 0 ]; then return 0; fi
    return 1
}
check_power() {
    CAP=\$(cat /sys/class/power_supply/battery/capacity 2>/dev/null)
    STAT=\$(cat /sys/class/power_supply/battery/status 2>/dev/null)
    if [ "\$CAP" -eq 100 ] && [[ "\$STAT" == "Charging" || "\$STAT" == "Full" ]]; then return 0; fi
    return 1
}
kill_miner() {
    local reason="\$1"
    if [ -f "\$MINER_PID_FILE" ]; then
        PID=\$(cat "\$MINER_PID_FILE")
        if [ -n "\$PID" ] && kill -0 "\$PID" 2>/dev/null; then
            echo "\$(date): Stopping miner. Reason: \$reason" >> "\$LOG_FILE"
            kill "\$PID"
        fi
        # Clear the PID file instead of removing it
        > "\$MINER_PID_FILE"
    fi
}
if [ ! -x "\$CPU_BIN" ]; then
    echo "\$(date): CRITICAL - Miner binary not found. Exiting." >> "\$LOG_FILE"
    exit 1
fi
while true; do
    if [ ! -f "\$MODE_FILE" ]; then echo "AUTO" > "\$MODE_FILE"; fi
    MODE=\$(cat "\$MODE_FILE")
    SHOULD_MINE=false; REASON=""
    if [ "\$MODE" == "FORCE_START" ]; then SHOULD_MINE=true
    elif [ "\$MODE" == "FORCE_STOP" ]; then SHOULD_MINE=false; REASON="Force Stop mode"
    else
        if check_power; then
            if ! is_screen_on; then SHOULD_MINE=true; else REASON="Screen is ON"; fi
        else REASON="Power not 100% and charging"; fi
    fi
    CURRENT_PID=\$(cat "\$MINER_PID_FILE")
    if [ "\$SHOULD_MINE" = true ]; then
        if [ -z "\$CURRENT_PID" ] || ! kill -0 "\$CURRENT_PID" 2>/dev/null; then
            echo "\$(date): Starting Miner (Mode: \$MODE)..." >> "\$LOG_FILE"
            nohup "\$CPU_BIN" -o "\$CPU_SERVER" -u "\$CPU_WALLET" -p "\$CPU_WORKER" --threads="\$CPU_THREADS" --cpu-no-yield --randomx-1gb-pages --donate-level=1 --config=/dev/null --no-color --log-file="\$LOG_FILE" --print-time=30 > /dev/null 2>&1 &
            echo \$! > "\$MINER_PID_FILE"
        fi
    else kill_miner "\$REASON"; fi
    sleep 5
done
EOF
    chmod +x "$WATCHDOG_SCRIPT"
}

start_watchdog() {
    fix_binary_path
    if ! command -v sudo &> /dev/null; then echo -e "${RED}Error: 'sudo' missing.${NC}"; return; fi

    stop_all
    echo "--- Startup Log ---" > "$DEBUG_LOG"
    sudo chmod -R 777 "$CONFIG_DIR" 2>/dev/null

    echo -e "${BLUE}Generating Watchdog Script...${NC}"
    generate_watchdog_script

    echo -e "${GREEN}Starting Service via Sudo...${NC}"
    sudo nohup "$TERMUX_BASH" "$WATCHDOG_SCRIPT" >> "$DEBUG_LOG" 2>&1 &
    sleep 2
    local PID; PID=$(pgrep -f "watchdog_runner.sh")

    if [ -n "$PID" ]; then
        echo "$PID" | sudo tee "$WATCHDOG_PID_FILE" > /dev/null
        echo -e "${GREEN}Success! Watchdog service is running (PID: $PID).${NC}"
        echo -e "${YELLOW}Check logs for miner status.${NC}"
    else
        echo -e "${RED}FAILED TO START WATCHDOG.${NC}"
        echo -e "${YELLOW}This may be a sudo or permissions issue.${NC}"
        echo -e "${YELLOW}Debug Details (from debug.log):${NC}"
        tail -n 10 "$DEBUG_LOG"
    fi
}

stop_all() {
    echo -e "${RED}Stopping all processes...${NC}"
    if [ -f "$WATCHDOG_PID_FILE" ]; then
        local WPID; WPID=$(cat "$WATCHDOG_PID_FILE")
        if [ -n "$WPID" ]; then sudo kill "$WPID" 2>/dev/null; fi
    fi
    sudo pkill -f watchdog_runner.sh
    sudo pkill -f xmrig
    sudo rm -f "$WATCHDOG_PID_FILE"
    # Don't remove the miner PID file, just clear it
    if [ -f "$MINER_PID_FILE" ]; then sudo sh -c '> "$MINER_PID_FILE"'; fi
    echo "Done."
}

set_mode() { echo "$1" > "$MODE_FILE"; echo -e "Mode set to: ${CYAN}$1${NC}"; }

# --- 5. MENU ---

show_status() {
    echo -e "\n${CYAN}--- STATUS (v11.3) ---${NC}"
    [ ! -f "$MODE_FILE" ] && echo "AUTO" > "$MODE_FILE"
    MODE=$(cat "$MODE_FILE")
    echo -e "Mode: ${CYAN}$MODE${NC}"

    if pgrep -f "watchdog_runner.sh" > /dev/null; then
        echo -e "Watchdog: ${GREEN}RUNNING${NC}"
    else
        echo -e "Watchdog: ${RED}STOPPED${NC}"
    fi

    # FIX: Use sudo to read the root-owned PID file and check the process status.
    local MINER_IS_RUNNING=false
    if [ -f "$MINER_PID_FILE" ]; then
        # Read the PID using sudo to overcome file permissions.
        local MINER_PID; MINER_PID=$(sudo cat "$MINER_PID_FILE")
        # Check if the PID is not empty and if the process exists (also with sudo).
        if [ -n "$MINER_PID" ] && sudo kill -0 "$MINER_PID" 2>/dev/null; then
            MINER_IS_RUNNING=true
        fi
    fi

    if [ "$MINER_IS_RUNNING" = true ]; then
        echo -e "Miner:    ${GREEN}RUNNING${NC}"
    else
        echo -e "Miner:    ${YELLOW}STOPPED${NC}"
    fi
    echo "---------------------------"
}

view_logs() {
    echo -e "${BLUE}1. Snapshot (Last 20 lines)${NC}"
    echo -e "${BLUE}2. Realtime Stream (Watch Hashrate)${NC}"
    echo -e "${BLUE}3. Clear Logs (Reset File)${NC}"
    read -p "> " lch
    case $lch in
        1) echo -e "${CYAN}--- LAST 20 LINES ---${NC}"; tail -n 20 "$LOG_FILE"; read -p "Press Enter...";;
        2) echo -e "${GREEN}Stream Started. Press CTRL+C to stop.${NC}"; sleep 1; trap 'echo -e "\n${YELLOW}Stream Stopped.${NC}"; sleep 1; return' INT; tail -f "$LOG_FILE"; trap - INT;;
        3) echo "--- Log Cleared ---" > "$LOG_FILE"; echo -e "${GREEN}Log file cleared.${NC}"; sleep 1;;
    esac
}

main_menu() {
    if [ ! -f "$ENV_FILE" ]; then install_deps; setup_config; fi
    fix_binary_path
    while true; do
        clear; echo -e "${BLUE}=== MINING MANAGER ===${NC}"; show_status
        echo "1. Set Mode: AUTO"; echo "2. Set Mode: FORCE START"; echo "3. Set Mode: FORCE STOP"
        echo "----------------------"; echo "4. START Watchdog (Sudo)"; echo "5. STOP Everything"
        echo "----------------------"; echo "6. Install / Re-Configure"; echo "7. Edit Config File Manually"; echo "8. View Logs / Clean Logs"; echo "9. Exit"
        read -p "> " c
        case $c in
            1) set_mode "AUTO" ;; 2) set_mode "FORCE_START" ;; 3) set_mode "FORCE_STOP" ;;
            4) start_watchdog; read -p "Press Enter..." ;; 5) stop_all; read -p "Press Enter..." ;;
            6) install_deps; setup_config ;; 7) nano "$ENV_FILE" ;; 8) view_logs ;; 9) exit 0 ;;
        esac
    done
}

main_menu
